version: '3.8'

services:
  nodejs-proxy:
    build: .
    container_name: webdav-proxy
    restart: unless-stopped
    ports:
      - "8320:3000"  # 主机端口:容器端口
    environment:
      - PORT=3000
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M